version: "3"

services:
  mc_main:
    image: itzg/minecraft-server:java17-jdk
    ports:
      - 25565:25565
      - 8100:8100 # BlueMap
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - EULA=true
      - VERSION=${VERSION}
      - TYPE=${TYPE}
      - MEMORY=${MEMORY}
      - WHITELIST_FILE=${WHITELIST_FILE}
    volumes:
      - ./whitelist.json:/whitelist.json
      - mc_main:/data

  mc_main_backups:
    image: itzg/mc-backup
    depends_on:
      mc_main:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "6h"
      RCON_HOST: mc_main
      INITIAL_DELAY: 0
    volumes:
      - mc_main:/data:ro
      - ./backups/mc_main:/backups

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  mc_main: {}
  prom_data: {}
  grafana_data: {}
